// Angular/countdown-timer-app/src/app/app.component.ts
import { Component, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: true
})
export class AppComponent implements OnDestroy {
  countdownSeconds: number = 0;
  displayTime: string = '';
  countdown: any;

  updateCountdownSeconds(event: Event) {
    const target = event.target as HTMLInputElement;
    this.countdownSeconds = parseInt(target.value);
  }

  startCountdown() {
    if (this.countdownSeconds <= 0 || isNaN(this.countdownSeconds)) {
      alert("Please enter a valid positive number.");
      return;
    }

    const endTime = Date.now() + this.countdownSeconds * 1000;

    this.countdown = setInterval(() => {
      const remainingTime = Math.round((endTime - Date.now()) / 1000);
      if (remainingTime < 0) {
        clearInterval(this.countdown);
        this.displayTime = "Time's up!";
      } else {
        const minutes = Math.floor(remainingTime / 60);
        const seconds = remainingTime % 60;
        this.displayTime = `${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;
      }
    }, 1000);
  }

  ngOnDestroy() {
    clearInterval(this.countdown);
  }
}
<div class="container">
    <h1 class="title">Countdown Timer</h1>
    <input class="input-field" type="number" [value]="countdownSeconds" (input)="updateCountdownSeconds($event)" placeholder="Enter time in seconds">
    <button class="start-button" (click)="startCountdown()">Start Countdown</button>
    <div class="timer">{{ displayTime }}</div>
  </div>

// React/timer/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [countdownSeconds, setCountdownSeconds] = useState(0);
  const [displayTime, setDisplayTime] = useState('');
  let countdown;

  const startCountdown = () => {
    if (!countdownSeconds || countdownSeconds <= 0) {
      alert("Please enter a valid positive number.");
      return;
    }

    const endTime = Date.now() + countdownSeconds * 1000;

    countdown = setInterval(() => {
      const remainingTime = Math.round((endTime - Date.now()) / 1000);
      if (remainingTime < 0) {
        clearInterval(countdown);
        setDisplayTime("Time's up!");
      } else {
        const minutes = Math.floor(remainingTime / 60);
        const seconds = remainingTime % 60;
        setDisplayTime(`${minutes}:${seconds < 10 ? '0' : ''}${seconds}`);
      }
    }, 1000);
  };

  useEffect(() => {
    return () => {
      clearInterval(countdown);
    };
  }, [countdown]);

  return (
    <div className="App">
      <h1>Countdown Timer</h1>
      <input type="number" value={countdownSeconds} onChange={(e) => setCountdownSeconds(parseInt(e.target.value))} placeholder="Enter time in seconds" />
      <button onClick={startCountdown}>Start Countdown</button>
      <div id="timer">{displayTime}</div>
    </div>
  );
}

export default App;
